# Configuraci�n de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dinastia_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=tu_usuario_de_mysql
spring.datasource.password=tu_contrase�a_de_mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor (opcional, por defecto es 8080)
server.port=8080
mercadopago.access.token=APP_USR-6385183089009932-031614-c10be3a78023affd380cdbe7eceaa665-3270626415

String img = (String) item.get("thumbnail");
p.setImagenUrl(img.replace("-I.jpg", "-O.jpg")); // El -O suele ser de mejor calidad